export class User {
  n_login: Number;
  n_questions: Number;
  ip_address: String;
  ref: String;
  auth_type:String;
  email: String;
  password: String;
  photo:String;
  code: Number;
  id: Number;
  time_signup: Number;
  username: String;
  premium: Number;
  time_paid: Number;
  premium_cfa2: Number;
  time_paid_cfa2: Number;
  premium_cfa_bundle: Number;
  time_paid_cfa_bundle: Number;
  premium_frm1: Number;
  time_paid_frm1: Number;
  premium_frm2: Number;
  time_paid_frm2: Number;
  premium_frm_bundle: Number;
  time_paid_frm_bundle: Number;
  exam_chosen: Number;
  imagelocation: String;
  name: String;
  location: String;
  exam_date: String;
  age: String;
  occupation: String;
  education: String;
  mock: Number;
  notes: Number;
  admin: Number;
  testmode: Number;
  confirmation: Number;
  mock_premium: Number;
  test: Number;
}
